### ISSUE TITLE
Table can't restart 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_Andorra_Table_Demo#1]
![image](https://user-images.githubusercontent.com/14296774/44920259-73931800-ad0d-11e8-9941-424a9d7494ef.png)

**Comment by doorleyr** [comment]
Changed the battery pack and restarted and it's fine now.

**Comment by RELNO** [comment]
Thanks @doorleyr  -- a fail safe code that checks if the controller is alive will be helpful, otherwise the demo cannot be restarted

**Comment by agrignard** [comment]
Fix in https://github.com/CityScope/CS_Andorra_Table_Demo/commit/762cde7cae293a9dcf6dd4c2f19b9e88987f0a82 by 

1. Adding a check in the code in case the controller is not connected
2. Adding the README that was in local on the demo machine that explained the different trouble shooting possible (in this case point 1.)
